import 'package:dio/dio.dart';

/// Typed error raised by repositories after a failed API call.
///
/// Thrown by Repository methods (which catch [DioException] and convert via
/// [ApiException.fromDioException]). UI layer maps `code` to user-facing
/// strings; `message` is a fallback only and should not be parsed.
///
/// `requestId` carries the `X-Request-ID` header from the failed response
/// (or the original request when there's no response). The error UI
/// surfaces it copy-to-clipboard so testers can paste it into bug reports —
/// matches the BE plan's "every request traceable end-to-end via a request
/// ID" goal (logging-plan.md).
class ApiException implements Exception {
  const ApiException({
    required this.code,
    required this.message,
    this.statusCode,
    this.details,
    this.requestId,
  });

  /// Stable, uppercase, snake-case identifier — clients key on this.
  final String code;

  /// Human-readable message from the backend. Fallback for unmapped codes.
  final String message;

  /// HTTP status, when available.
  final int? statusCode;

  /// Optional structured details (e.g. per-field errors for `VALIDATION_ERROR`).
  final Map<String, dynamic>? details;

  /// `X-Request-ID` echoed by the response, or the value the FE sent
  /// when there's no response (timeout, connection error). Used for
  /// log correlation across FE + BE.
  final String? requestId;

  /// Convert a raw [DioException] into an [ApiException]. Recognises both the
  /// backend's `{ "error": { "code", "message" } }` envelope and pure transport
  /// failures (timeouts, no connection).
  factory ApiException.fromDioException(DioException e) {
    final response = e.response;
    final data = response?.data;
    final reqId = _extractRequestId(e);

    if (data is Map && data['error'] is Map) {
      final err = data['error'] as Map;
      return ApiException(
        code: (err['code'] as String?) ?? 'UNKNOWN_ERROR',
        message: (err['message'] as String?) ?? e.message ?? 'Unknown error',
        statusCode: response?.statusCode,
        details: err['details'] is Map
            ? Map<String, dynamic>.from(err['details'] as Map)
            : null,
        requestId: reqId,
      );
    }

    final code = switch (e.type) {
      DioExceptionType.connectionTimeout ||
      DioExceptionType.sendTimeout ||
      DioExceptionType.receiveTimeout =>
        'NETWORK_TIMEOUT',
      DioExceptionType.connectionError => 'NETWORK_ERROR',
      DioExceptionType.cancel => 'REQUEST_CANCELLED',
      _ => 'UNKNOWN_ERROR',
    };

    return ApiException(
      code: code,
      message: e.message ?? 'Network error',
      statusCode: response?.statusCode,
      requestId: reqId,
    );
  }

  /// Pull the request id from the response header first (BE may have
  /// echoed/replaced it), else from the request header (FE-generated by
  /// HttpLoggerInterceptor).
  static String? _extractRequestId(DioException e) {
    final fromResponse = e.response?.headers.value('x-request-id');
    if (fromResponse != null && fromResponse.isNotEmpty) return fromResponse;
    final fromRequest = e.requestOptions.headers['X-Request-ID'];
    if (fromRequest is String && fromRequest.isNotEmpty) return fromRequest;
    return null;
  }

  @override
  String toString() => 'ApiException($code: $message${requestId != null ? " req=$requestId" : ""})';
}
